### ISSUE TITLE
Feature request: Save support

### ISSUE THREAD

**Issue by mewmew** [quixotic-cynic/open-diablo-editor#4]
I know you are already aware of this, as the rewrite of ODE doesn't currently support saving. Creating this issue to have a future reference (which may be tracked in code changes; e.g. using `updates #4` in the git commit messages).

For reference: https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by quixotic-cynic** [comment]
Basic save support is now complete. A further issue has been created for advanced/improved save support. Closing this ticket.

**Comment by mewmew** [comment]
Lovely : )
